fix: application test 4

diff --git a/.releaserc.yaml b/.releaserc.yaml
--- a/.releaserc.yaml
+++ b/.releaserc.yaml
@@ -36,11 +36,16 @@ plugins:
       changelogTitle: "# Changelog"
   - - "@semantic-release/exec"
     - prepareCmd: >
-        mvn versions:set -DnewVersion=${nextRelease.version} || { echo "Failed to update Maven version"; exit 1; } &&
+        mvn versions:set -DnewVersion=${nextRelease.version} &&
         echo "NEXT_VERSION=${nextRelease.version}" >> build.env
   - - "@semantic-release/exec"
     - prepareCmd: >
         set -e;
+        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD);
+        if [[ ! $CURRENT_BRANCH =~ ^release/v.*-(alpha|beta)$ ]]; then
+          echo "Error: Current branch $CURRENT_BRANCH does not match pre-release pattern release/v*-alpha or release/v*-beta";
+          exit 1;
+        fi;
         git fetch origin master;
         git checkout master;
         git pull origin master;
